---
apiVersion: v1
kind: Pod
metadata:
        name: my-pod
        labels:
         tier: live
spec:
        containers:
         - name: busy
           image: busybox
           args:
           - "/bin/sh"
           - "-c"      
           - "touch /tmp/file1; sleep 30; rm -rf /tmp/file1; sleep 30"
           livenessProbe:
            exec:
             command:
              - echo "my name is laptop>/tmp/file1"
            initialDelaySeconds: 5
            periodSeconds: 5
...      
