---
apiVersion: v1
kind: Pod
metadata:
 name: jenkins-pod
 labels:
  type: ci-cd
  author: intelliqit
spec:
 containers:
  - name: sonarqube
    image: sonarqube
    ports:
     - containerPort: 9000
       hostPort: 8080   
...
