---
apiVersion: v1
kind: Service
metadata:
   name: my-service
   labels:
      auth: serve
spec:
   clusterIP: None
   ports:
      - name: serve
        port: 80
   selector:
      auth: nginx
--- 
apiVersion: apps/v1
Kind: StatefulSet
metadata:
   name: my-stateful
   labels:
      auth: serve
spec:
   selector:
      matchLabels:
         auth: serve
   serviceName: my-service
   replicas: 3         
        template:
            metadata:
               labels:
                  auth: serve
            spec:
               - name: ngi
                 image: nginx
                 ports:
                    - containerPort: 80
                 volumeMounts:
                    - name: my-volume
                      mountPath: /var/
volumeClaimTemplates:
    metadata:
       name: my-volume
    spec:
       accessModes: ["ReadWriteOnce"]   

      
















